version: '2'
services:
  ycsrv:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./srv:/app
      - ./dist:/dist
      - ./log:/log
    environment:
      - DEBUG=*,-mquery
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://localhost:27018/yc
      - listenport=6012
      - tcpport=50000
      - admindir=/dist/admin
      - apppcdir=/dist/pcapp
      - logdir=/log
    network_mode: "host"
    ports:
       - "6012:6012"
       - "50000:50000"
    expose:
       - "6012"
       - "50000"
